name: PyLint for project Leaf

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Python Pylint Github Action
      uses: fylein/python-pylint-github-action@v4
